[metadata]
name = probtf-integrated
version = 0.1.0
description = ProbTF, symmetry-aware grasping, and deflection compensation
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT

[options]
python_requires = >=3.8
install_requires =
    numpy>=1.20
    numpy-quaternion>=2022.4.3
    pin>=2.6
    PyYAML>=5.3
    scipy>=1.6
include_package_data = True

[options.extras_require]
examples =
    ikpy>=3.3
    matplotlib>=3.3
test =
    pytest>=6
visualization =
    matplotlib>=3.3

[options.entry_points]
console_scripts =
    deflecomp-flexible-demo = deflecomp_examples.simulator_flexible:main
    deflecomp-offline-demo = deflecomp_examples.offline_demo:main

[tool:pytest]
testpaths = tests
